Bug Fixed in get_templates
An error occurs when I run the pipeline.
TypeError: get_templates() got an unexpected keyword argument 'hhr_hits'

template_featurizer.get_templates() expects the variable called hits